config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root 'admin/dashboard#index', as: :admin_root
  end

  authenticated :user, ->(user) { user.trader? } do
    root 'trader/dashboard#index', as: :trader_root
  end

  root 'pages#landing'

  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    },
    controllers: {
      sessions: 'users/sessions',
      invitations: 'users/invitations'
    },
    skip: [:registrations]

  # routes for user registrations controller
  devise_scope :user do
    get '/register', to: 'users/registrations#new', as: :new_user_registration
    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    post 'users', to: 'users/registrations#create', as: :user_registration
    put 'users', to: 'users/registrations#update', as: :update_user_registration
    delete 'users', to: 'users/registrations#destroy', as: :destroy_user_registration
  end

  namespace :admin do
    resources :users, except: [:new, :create]
    resources :transactions, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :trader, path: 't' do
    resources :transactions, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    get 'market', to: 'dashboard#market', as: :market_page
    get 'cash-in', to: 'cash_in#index'
    patch 'cash-in', to: 'cash_in#update'
    get 'withdraw', to: 'withdraw#index'
    patch 'withdraw', to: 'withdraw#update'
    get 'trade', to: 'trades#index'
    post 'trade/buy', to: 'trades#buy'
    post 'trade/sell', to: 'trades#sell'
    get 'portfolio', to: 'portfolios#index'
  end

  resources :statuses, only: [:edit, :update]

  # routes for static pages
  get 'landing', to: 'pages#landing', as: :landing_page
  get 'pending-verification', to: 'pages#pending_verification', as: :pending_verification_page

  # for route error
  match "*path", to: "application#no_path_found", via: :all
end

app/controllers/trader/cash_in_controller.rb
class Trader::CashInController < TradersController
  before_action :ensure_frame_response, except: [:update]
  layout 'dashboard_layout'

  include CurrencyHelper

  def index
    @balance = current_user.balance
  end

  def update
    amount = params[:amount].to_f

    if Transaction.cash_in(current_user, amount)
      flash[:notice] = "Successfully cashed in #{format_currency(amount, unit: '$')}."
    else
      flash[:alert] = 'Failed to cash in. Please try again.'
    end
    redirect_to trader_dashboard_path
  end

  private

  def ensure_frame_response
    return if Rails.env.test?
    redirect_to trader_dashboard_path unless turbo_frame_request?
  end
end

app/controllers/trader/dashboard_controller.rb
class Trader::DashboardController < TradersController
  layout 'dashboard_layout'

  def index
    @total_portfolio_value = 0.0

    # Fetch quote for each stock
    @stock_quotes = {}
    @stocks.each do |stock|
      stock_symbol = stock[:stock_symbol]
      @stock_quotes[stock_symbol] = IEX::Api::Client.new.quote(stock_symbol)

      total_price = @stock_quotes[stock_symbol].latest_price * stock[:total_shares]
      @total_portfolio_value += total_price
    end
  end

  def market
  end

end

app/controllers/trader/portfolios_controller.rb
class Trader::PortfoliosController < TradersController
  layout 'dashboard_layout'

  def index
    @stocks = Stock.group_similar_stocks(current_user)

    if params[:sort_by] == 'asc'
      @stocks.sort_by! { |stock| stock[:total_shares] }
    elsif params[:sort_by] == 'desc'
      @stocks.sort_by! { |stock| -stock[:total_shares] }
    end

    @pagy, @stocks = pagy_array(@stocks) || pagy(@stocks) # pagy stuff
    @total_portfolio_value = 0.0

    # to fetch quote for each stock
    @stock_quotes = {}
    @stocks.each do |stock|
      stock_symbol = stock[:stock_symbol]
      @stock_quotes[stock_symbol] = IEX::Api::Client.new.quote(stock_symbol)

      total_price = @stock_quotes[stock_symbol].latest_price * stock[:total_shares]
      @total_portfolio_value += total_price
    end
  end
end

app/controllers/trader/trade_controller.rb
class Trader::TradeController < ApplicationController
  layout 'dashboard_layout'

  def index
    @trader_status = current_user.status&.status_type
    return unless params[:symbol].present?

    @stock_symbol = params[:symbol].to_s.upcase

    begin
      @data = IEX::Api::Client.new.quote(@stock_symbol)
    rescue IEX::Errors::SymbolNotFoundError => e
      flash[:alert] = "Stock symbol not found: #{@stock_symbol}"
      redirect_to trader_trade_path
    end
  end

  def buy
    @stock_symbol = params[:symbol].to_s.upcase
    @data = IEX::Api::Client.new.quote(@stock_symbol)
    shares = params[:shares].to_i
    price_per_share = @data.latest_price
    total_cost = price_per_share * shares

    if current_user.balance >= total_cost
      # Update user's balance
      current_user.update(balance: current_user.balance - total_cost)
      flash[:notice] = 'Stock purchased successfully'
      # Record the transaction
      Transaction.create!(
        user: current_user,
        transaction_type: 'buy',
        stock_symbol: @data.symbol,
        shares:,
        price_per_share:
      )

    else
      flash[:alert] = 'Insufficient balance'
    end
  end
end

app/controllers/trader/trades_controller.rb
class Trader::TradesController < TradersController
  before_action :set_params
  layout 'dashboard_layout'

  def index
    return unless params[:stock_symbol].present?
    @data = IEX::Api::Client.new.quote(@stock_symbol)
    @stock = Stock.find_by(stock_symbol: @stock_symbol)
    @total_shares = @stock ? @stock.total_shares(current_user) : 0.0

  rescue IEX::Errors::SymbolNotFoundError => e
    flash[:alert] = "NASDAQ symbol '#{@stock_symbol}' not found."
    redirect_to trader_trade_path
  end

  def buy
    if Transaction.buy_shares(current_user, @stock_symbol, @shares)
      flash[:notice] = "#{@stock_symbol} stock purchased successfully"
      redirect_to trader_portfolio_path
    else
      error_message = if current_user.errors.any?
                        current_user.errors.full_messages.join('. ')
                      else
                        'Oops. There was a problem in buying stock shares.'
                      end
      flash[:alert] = error_message
      redirect_back(fallback_location: trader_trade_path)
    end
  end

  def sell
    if Transaction.sell_shares(current_user, @stock_symbol, @shares)
      flash[:notice] = "#{@stock_symbol} stock sold successfully"
      redirect_to trader_portfolio_path
    else
      error_message = if current_user.errors.any?
                        current_user.errors.full_messages.join('. ')
                      else
                        'Oops. There was a problem in selling stock shares.'
                      end
      flash[:alert] = error_message
      redirect_back(fallback_location: trader_trade_path)
    end
  end

  private

  def set_params
    @stock_symbol = params[:stock_symbol].gsub(/[^a-zA-Z0-9\-.]/, '').upcase if params[:stock_symbol].present?
    @shares = params[:buy_shares].to_f if params[:buy_shares].present?
    @shares = params[:sell_shares].to_f if params[:sell_shares].present?
  end

end

app/controllers/trader/transactions_controller.rb
class Trader::TransactionsController < TradersController
  layout 'dashboard_layout'

  def index
    @transactions = current_user.transactions.includes(:stock).filter_by_type(params[:filter]).order(updated_at: :desc)
    @transaction_types = Transaction::TRANSACTION_TYPES
    @pagy, @transactions = pagy(@transactions)
  end
end

app/controllers/trader/withdraw_controller.rb
class Trader::WithdrawController < TradersController
  before_action :ensure_frame_response, except: [:update]
  layout 'dashboard_layout'

  include CurrencyHelper

  def index
    @balance = current_user.balance
  end

  def update
    amount = params[:amount].to_f

    if Transaction.withdraw(current_user, amount)
      flash[:notice] = "Successfully cashed out #{format_currency(amount, unit: '$')}."
    else
      flash[:alert] = 'Failed to withdraw. Please try again.'
    end
    redirect_to trader_dashboard_path
  end

  private

  def ensure_frame_response
    return if Rails.env.test?
    redirect_to trader_dashboard_path unless turbo_frame_request?
  end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
  before_action :authorize_trader, :check_status, :set_trader_status, :set_stock_symbol, :set_stocks_per_trader

  private

  def authorize_trader
    redirect_to root_path, alert: "Access denied. You are not a trader." unless current_user.trader?
  end

  def check_status
    return unless current_user.trader? && @trader_status == 'pending' && !current_user.confirmed?

    sign_out(current_user)
    redirect_to pending_verification_page_path
  end

  def set_trader_status
    @trader_status = current_user.status&.status_type
  end

  def set_stock_symbol
    @stock_symbol = params[:stock_symbol].to_s.upcase
  end

  def set_stocks_per_trader
    @stocks = Stock.group_similar_stocks(current_user)
  end
end

app/helpers/trader/dashboard_helper.rb
module Trader::DashboardHelper
end

app/helpers/trader/withdraw_helper.rb
module Trader::WithdrawHelper
end

app/helpers/traders_helper.rb
module TradersHelper
end

app/views/trader/trades/index.html.erb
<% content_for :header do %>
  <div class="flex justify-between w-full">
    <div class="flex gap-3 items-center w-2/3">
      Trade Stocks
      <p class="text-base text-gray-500">
        Trade Responsibly
      </p>
    </div>
    <div class="w-1/3 form__wrapper px-0">
      <%= form_tag(trader_trade_path, method: :get) do %>
        <div class="flex justify-center gap-2 w-full">
          <div class="field flex-col lg:flex-row gap-2 w-full items-center">
            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
              <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="m21 21-3.5-3.5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z"/>
            </svg>
            <%= text_field_tag :stock_symbol, params[:stock_symbol], placeholder: "Enter NASDAQ Stock Symbol", class:"w-full text-xs" %>
          </div>
          <%= submit_tag "Search", class:"text-xs button--main cursor-pointer" %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class="h-full flex flex-col gap-4">
  <%= render 'pages/widgets/ticker' %>
  <div class="flex flex-col gap-1 w-full h-full">
    <div class="flex w-full h-full flex-col gap-1">
      <%= render 'pages/widgets/fixed_chart', locals: { stock_symbol: @stock_symbol } %>
      <% if @data.present? %>
        <div class="flex gap-1 h-fit w-full">
          <div class="bg--frosted py-2 px-4 flex flex-col gap-2 items-center justify-around h-full w-full">
            <!-- ** FORMS ** -->
            <div class="h-full w-auto flex gap-2 py-2 divide-x-2 divide-gray-600 text-sm">
              <!-- ** BUY FORM ** -->
              <div class="buy-form h-full px-8 py-2">
                <%= form_with(url: trader_trade_buy_path, method: :post1) do |form| %>
                  <div class="form__wrapper gap-2 items-center">
                    <div class="field gap-6 flex-row items-center w-full">
                      <small class="font-light font-sans w-fit">Current balance:</small>
                      <small><%= format_currency(current_user.balance, unit:"$ ") %></small>
                    </div>
                    <div class="field gap-6 flex-row items-center w-full">
                      <%= form.hidden_field :stock_symbol, value: params[:stock_symbol] %>
                      <%= form.label :buy_shares, "Share Qty:", class: "w-1/2" %>
                      <%= form.number_field :buy_shares, min: 0, step: 0.01, class: "w-full" %>
                    </div>
                    <%= form.button 'Buy', class:"modal__button button--green" %>
                  </div>
                <% end %>
              </div>
              <!-- ** SELL FORM ** -->
              <div class="sell-form h-full px-8 py-2">
                <%= form_with(url: trader_trade_sell_path, method: :post) do |form| %>
                  <div class="form__wrapper gap-2 items-center">
                    <div class="field gap-6 flex-row items-center w-full">
                      <small class="font-light font-sans w-fit">Current shares:</small>
                      <small><%= @total_shares %></small>
                    </div>
                    <div class="field gap-4 flex-row items-center w-full">
                      <%= form.hidden_field :stock_symbol, value: params[:stock_symbol] %>
                      <%= form.label :sell_shares, "Share Qty:", class: "w-1/2" %>
                      <%= form.number_field :sell_shares, min: 0, step: 0.01, class: "w-full" %>
                    </div>
                    <%= form.button 'Sell', class:"modal__button button--purple" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <%= render 'pages/widgets/top_news' %>
      <% end %>
    </div>
  </div>
</div>