config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root 'admin/dashboard#index', as: :admin_root
  end

  authenticated :user, ->(user) { user.trader? } do
    root 'trader/dashboard#index', as: :trader_root
  end

  root 'pages#landing'

  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    },
    controllers: {
      sessions: 'users/sessions',
      invitations: 'users/invitations'
    },
    skip: [:registrations]

  # routes for user registrations controller
  devise_scope :user do
    get '/register', to: 'users/registrations#new', as: :new_user_registration
    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    post 'users', to: 'users/registrations#create', as: :user_registration
    put 'users', to: 'users/registrations#update', as: :update_user_registration
    delete 'users', to: 'users/registrations#destroy', as: :destroy_user_registration
  end

  namespace :admin do
    resources :users, except: [:new, :create]
    resources :transactions, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :trader, path: 't' do
    resources :transactions, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    get 'market', to: 'dashboard#market', as: :market_page
    get 'cash-in', to: 'cash_in#index'
    patch 'cash-in', to: 'cash_in#update'
    get 'withdraw', to: 'withdraw#index'
    patch 'withdraw', to: 'withdraw#update'
    get 'trade', to: 'trades#index'
    post 'trade/buy', to: 'trades#buy'
    post 'trade/sell', to: 'trades#sell'
    get 'portfolio', to: 'portfolios#index'
  end

  resources :statuses, only: [:edit, :update]

  # routes for static pages
  get 'landing', to: 'pages#landing', as: :landing_page
  get 'pending-verification', to: 'pages#pending_verification', as: :pending_verification_page

  # for route error
  match "*path", to: "application#no_path_found", via: :all
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  balance                :decimal(10, 2)   default(0.0)
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  invitation_accepted_at :datetime
#  invitation_created_at  :datetime
#  invitation_limit       :integer
#  invitation_sent_at     :datetime
#  invitation_token       :string
#  invitations_count      :integer          default(0)
#  invited_by_type        :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  role                   :enum             default("trader"), not null
#  uid                    :string
#  unconfirmed_email      :string
#  username               :string           default(""), not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  invited_by_id          :bigint
#
# Indexes
#
#  index_users_on_confirmation_token    (confirmation_token) UNIQUE
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_invitation_token      (invitation_token) UNIQUE
#  index_users_on_invited_by            (invited_by_type,invited_by_id)
#  index_users_on_invited_by_id         (invited_by_id)
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_uid                   (uid) UNIQUE
#  index_users_on_username              (username) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :recoverable, :rememberable,
         :validatable, :uid, :confirmable, authentication_keys: [:login]

  has_one :status, dependent: :destroy
  accepts_nested_attributes_for :status

  has_many :transactions, dependent: :destroy
  has_many :stocks, through: :transactions

  enum :role, {
    admin: 'admin',
    trader: 'trader'
  }, default: 'trader'

  attr_accessor :login
  STATUS_TYPES = Status.status_types.keys # => ["pending", "approved", "confirmed_email"]

  validates :email, presence: true, uniqueness: true
  validates :balance, numericality: { greater_than_or_equal: 0, message: "Insufficient balance." }
  validates :username, length: {in: 5..20}, uniqueness: true
  validates :password, presence: true, on: :create

  before_create :initialize_status_for_trader
  after_invitation_accepted :update_status_of_invited_user

  scope :approved_traders, -> { includes(:status).where(role: :trader, statuses: { status_type: "approved" }) }
  scope :pending_traders, -> { includes(:status).where(role: :trader, statuses: { status_type: "pending" }).order(:created_at) }
  scope :confirmed_email_traders, -> { includes(:status).where(role: :trader, statuses: { status_type: "confirmed_email" }).order(:updated_at) }
  scope :filter_by_status, ->(filter) {
    if STATUS_TYPES.include?(filter)
      where(status_type: filter)
    else
      sorted_traders
    end
  }

  def self.sorted_traders(traders)
    traders.to_a.sort_by do |trader|
      case trader.status.status_type
      when "pending"
        1
      when "confirmed_email"
        2
      when "approved"
        3
      else
        4
      end
    end
  end

  ## DEVISE STUFF
  # for adding username on login
  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup

    if (login = conditions.delete(:login))
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value',
                                    { value: login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  # updating status of confirmed email (devise confirmable)
  def after_confirmation
    super
    status.update(status_type: 'confirmed_email') if status.present?
  end

  ## RANSACK STUFF
  # whitelisting params for search
  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end

  def self.ransackable_associations(auth_object = nil)
    authorizable_ransackable_associations
  end

  private

  def initialize_status_for_trader
    return unless trader?
    build_status(status_type: 'pending')
  end

  def update_status_of_invited_user
    status.update(status_type: "confirmed_email")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsController
  before_action :set_trader, except: [:index]
  before_action :ensure_frame_response, only: [:show, :edit]
  layout "admin_layout"

  def index
    @q = User.includes(:status).where(role: :trader).ransack(params[:q])
    @traders = @q.result(distinct: true)
    @traders = User.sorted_traders(@traders)

    if params[:q].present? && @traders.empty?
      flash[:alert] = "Hmm. Please try searching for something else."
      redirect_to admin_users_path
    end

    if params[:filter].present? && User::STATUS_TYPES.include?(params[:filter])
      @traders = User.includes(:status).where(role: :trader, statuses: { status_type: params[:filter] })
    end

    @status_types = User::STATUS_TYPES
    @pagy, @traders = pagy_array(@traders) || pagy(@traders)
  end

  def show
    @stocks = Stock.group_similar_stocks(@trader)
  end

  def edit
  end

  def update
    if @trader.update(trader_params)
      flash[:notice] = "Admin has successfully updated the details of #{@trader.email}."
      redirect_to admin_users_path
    else
      flash[:alert] = @trader.errors.full_messages.join(". ")
      render :edit, status: 422
    end
  end

  def destroy
    @trader.destroy
    redirect_to admin_users_path, notice: "Admin permanently deleted #{@trader.email}."
  end

  private

  def set_trader
    @trader = User.includes(:status).find(params[:id])
  end

  def trader_params
    params.require(:user).permit(:username, :email, status_attributes: [:status_type, :id])
  end

  def ensure_frame_response
    return if Rails.env.test?
    redirect_to admin_users_path unless turbo_frame_request?
  end
end

app/controllers/users/invitations_controller.rb
# frozen_string_literal: true

class Users::InvitationsController < Devise::InvitationsController
  before_action :validate_uniqueness, only: :create

  def create
    super
  end

  def after_invite_path_for(_inviter, _invitee)
    admin_dashboard_path
    # insert alert notice here
  end

  private

  def validate_uniqueness
    email = params[:user][:email]
    username = email.split('@').first.downcase # Assuming username is derived from the part before the @ symbol

    return unless User.exists?(email:) || User.exists?(username:)

    self.resource = resource_class.new(invite_params)
    resource.errors.add(:base, 'Email or username is already taken')
    render :new
  end

  def after_accept_path_for(resource)
    trader_dashboard_path
  end

  def invite_params # GPT
    params.require(:user).permit(:email, :role).tap do |whitelisted|
      whitelisted[:username] = params[:user][:email].split('@').first if params[:user][:email].present?
    end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout :set_layout, only: [:edit, :update]

  private

  def set_layout
    if current_user.trader?
      "dashboard_layout"
    else
      "admin_layout"
    end
  end

  def after_inactive_sign_up_path_for(resource)
    pending_verification_page_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_delete_user_modal.html.erb
<dialog id="delete_modal">
  <div aria-labelledby="modal-title" aria-modal="true" class="fixed inset-0 z-30 overflow bg-black/80" role="dialog">
    <div class="h-screen w-full relative flex items-center justify-center">
      <div class="relative rounded-lg shadow bg-gray-700 w-1/3 px-4 py-2">
        <form method="dialog">
          <%= link_to admin_users_path, class: "absolute top-3 end-2.5 text-gray-400 bg-transparent rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center hover:bg-gray-600 hover:text-white" do %>
            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
            </svg>
          <% end %>

          <div class="p-4 md:p-5 text-center">
            <div class="flex items-center justify-center gap-3 py-4">
              <svg class="lex-shrink-0 w-10 h-10 transition duration-75 text-gray-400 group-hover:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11V6m0 8h.01M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
              </svg>
            </div>
            <h3 class="mb-5 text-sm font-normal text-gray-200 font-sans">Are you sure you want to permanently delete this trader?</h3>
            
            <button value="confirm" class="text-white bg-violet-600 hover:bg-violet-800 focus:ring-4 focus:outline-none focus:ring-violet-300 dark:focus:ring-violet-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center font-sans">
              Continue
            </button>
            
            <button value="cancel" class="py-2.5 px-5 ms-3 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-100 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 font-sans">
              No, cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</dialog>

app/views/admin/users/_form.html.erb
<%= form_with model: trader, url: admin_user_path(trader), method: :patch, data: { turbo: false } do |f| %>
  <div class="form__wrapper">
    <div>
      <%= f.label :username, class: "modal__label" %> 
      <%= f.text_field :username, autofocus: true, autocomplete: "username", class: "modal__textfield", id: "user_username_#{trader.id}" %>
    </div>

    <div>
      <%= f.label :email, class: "modal__label" %> 
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "modal__textfield", id: "user_email_#{trader.id}" %>
    </div>
    
    <%= f.fields_for :status do |builder| %>
      <div class="field flex-row items-center gap-2 px-px <%= trader.status.status_type == 'approved' ? 'hidden' : 'inline-flex' %>">
        <%= builder.check_box :status_type, { checked: false, id: "status_type_#{trader.id}_#{builder.object.id}" }, 'approved', nil %>
        <%= builder.label "status_type_#{trader.id}_#{builder.object.id}", "Approve", class: "text-white font-medium" %>   
      </div>

      <%= builder.hidden_field :id, id: "user_status_attributes_id_#{trader.id}" %>
    <% end %>

    <%= f.button "Save Changes", class: "modal__button button--green" %>
  </div>
<% end %>

app/views/admin/users/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#destroy</h1>
  <p>Find me in app/views/admin/users/destroy.html.erb</p>
</div>

app/views/admin/users/edit.html.erb
<%= turbo_frame_tag "edit_modal" do %>
  <%= tag.div data: { controller: "modals" } do %>

    <div aria-labelledby="modal-title" aria-modal="true" class="fixed inset-0 z-30 overflow bg-black/80" role="dialog">
      <div class="edit-modal h-screen w-full relative flex items-center justify-center">
        <div class="relative rounded-lg shadow bg-gray-700 w-1/3 px-4 py-2">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
            <h3 class="font-sans text-xl font-semibold text-gray-900 dark:text-white">
                Edit User Details
            </h3>

            <%= button_to "#", data: { action: "modals#hideModal" }, class: "end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" do %>
              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
              </svg>
            <% end %>
          </div>
            
          <!-- Modal body -->
          <div class="p-4 md:p-5 flex flex-col gap-3">
            <%= render 'form', trader: @trader %>
          </div>
        </div> 
      </div>
    </div>

  <% end %>
<% end %>

app/views/admin/users/index.html.erb
<% content_for :header do %>
  <div class="flex justify-between items-center w-full py-2">
    All Traders
    <div class="text-xs w-1/4">
      <%= render 'shared/filter_transactions', { resource: "Traders", path: admin_users_path, filter_array: @status_types } %>
    </div>
  </div>
<% end %>
<div class="relative  sm:rounded-lg text-sm flex flex-col gap-4 w-full">
  <!--** SEARCH BAR ** -->
  <div class="flex items-center gap-2 pr-6">
    <%= render 'shared/ransack_search_bar', { path: admin_users_path, params: :email_or_username_or_uid_cont, placeholder: "Search Trader" } %>
  </div>

  <% if @traders.present? %>
    <table class="w-full shadow-md text-sm text-left rtl:text-right text-gray-400">
      <thead class="text-xsuppercase bg-gray-700/55 text-gray-400">
        <tr>
          <th scope="col" class="px-6 py-3">
            Email
          </th>
          <th scope="col" class="px-6 py-3">
            Username
          </th>
          <th scope="col" class="px-6 py-3">
            UID
          </th>
          <th scope="col" class="px-6 py-3">
            Status
          </th>
          <th scope="col" class="px-6 py-3">
            <span class="sr-only">Actions</span>
          </th>
        </tr>
      </thead>
      <tbody>
        <% @traders.each do |trader| %>
          <tr class="border-b bg-stone-900/35 border-gray-700 hover:bg-gray-600">
            <th scope="row" class="px-6 py-3 font-medium whitespace-nowrap text-white">
              <%= trader.email %>
            </th>
            <td class="px-6 py-2.5">
              <%= trader.username %>
            </td>
            <td class="px-6 py-2.5">
              <%= trader.uid %>
            </td>
            <td class="px-6 py-2.5">
              <%= trader.status.status_type %>
            </td>
            <td class="w-fit h-fit">
              <div class="modal-btns flex items-center gap-2 justify-center">
                <%= link_to admin_user_path(trader), data: { turbo_frame: 'show_modal' }, class: "info-btn block text-white focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-4 py-2 text-center bg-blue-600 hover:bg-blue-700 focus:ring-blue-800" do %>
                  <svg class="w-5 h-5 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 11h2v5m-2 0h4m-2.592-8.5h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                  </svg>
                <% end %>
                <%= link_to edit_admin_user_path(trader), data: { turbo_frame: 'edit_modal' }, class: "edit-btn block text-white focus:ring-4 focus:outline-none font-medium rounded-lg text-sm pr-3 pl-4 py-2 text-center bg-teal-600 hover:bg-teal-700 focus:ring-teal-800" do %>
                  <svg class="w-5 h-5 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m14.304 4.844 2.852 2.852M7 7H4a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h11a1 1 0 0 0 1-1v-4.5m2.409-9.91a2.017 2.017 0 0 1 0 2.853l-6.844 6.844L8 14l.713-3.565 6.844-6.844a2.015 2.015 0 0 1 2.852 0Z"/>
                  </svg>
                <% end %>
                <%= link_to admin_user_path(trader), data: { turbo_method: :delete, turbo_confirm: "You are about to permanently delete #{trader.email}" }, class: "delete-btn block text-white focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-4 py-2 text-center bg-violet-600 hover:bg-violet-700 focus:ring-violet-800" do %>
                  <svg class="w-5 h-5 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
                  </svg>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <% else %>
    <div class="h-full w-full flex flex-col gap-1 justify-center items-center mt-4">
      <h1>No trader found</h1>
    </div>
  <% end %>
</div>
<!-- Delete confirmation modal -->
<%= render 'delete_user_modal' %>
<!--** TURBO_FRAME MODALS **-->
<%= turbo_frame_tag "show_modal" %>
<%= turbo_frame_tag "edit_modal" %>
<!-- *** Render a view helper in your views (skipping nav links for empty pages)*** -->
<div class=" grid place-items-center py-2.5">
  <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/admin/users/show.html.erb
<%= turbo_frame_tag "show_modal" do %>
  <%= tag.div data: { controller: "modals" } do %>
    <div aria-labelledby="modal-title" aria-modal="true" class="fixed inset-0 z-30 overflow bg-black/80" role="dialog">
      <div class="h-screen w-full relative flex items-center justify-center">
        <div class="relative rounded-lg shadow bg-gray-700 w-1/3 px-4 py-2">
          <!-- Modal header -->
          <div class="flex items-center justify-between p-4 md:p-5 border-b rounded-t dark:border-gray-600">
            <h3 class="font-sans text-xl font-semibold text-gray-900 dark:text-white">
              User Details
            </h3>
            <%= button_to "#", data: { action: "modals#hideModal" }, class: "end-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm w-8 h-8 ms-auto inline-flex justify-center items-center dark:hover:bg-gray-600 dark:hover:text-white" do %>
              <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
              </svg>
            <% end %>
          </div>
          <!-- Modal body -->
          <div class="p-4 md:p-5 flex flex-col gap-3">
            <span>Email: <span class="font-bold text-white"><%= @trader.email %></span></span>
            <span>Balance: <span class="font-bold text-white"><%= format_currency(@trader.balance, unit: "$") %></span></span>
            <% if @trader.stocks.present? %>
              <table class="w-full text-sm text-left rtl:text-right text-gray-400">
                <thead class="text-xs font-sans uppercase bg-gray-700/55 text-gray-400">
                  <tr>
                    <th scope="col" class="px-6 py-3">
                      Symbol
                    </th>
                    <th scope="col" class="px-6 py-3">
                      Company Name
                    </th>
                    <th scope="col" class="px-6 py-3">
                      SHARES
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @stocks.each do |stock| %>
                    <tr class="border-b bg-stone-900/35 border-gray-700 hover:bg-gray-600">
                      <td class="px-6 py-2.5 font-sans font-bold text-violet-100">
                        <%= stock[:stock_symbol].upcase %>
                      </td>
                      <td class="px-6 py-2.5 font-sans text-emerald-50">
                        <%= stock[:company_name] %>
                      </td>
                      <td class="px-6 py-2.5">
                        <%= stock[:total_shares] %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/users/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Users#update</h1>
  <p>Find me in app/views/admin/users/update.html.erb</p>
</div>