config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  authenticated :user, ->(user) { user.admin? } do
    root 'admin/dashboard#index', as: :admin_root
  end

  authenticated :user, ->(user) { user.trader? } do
    root 'trader/dashboard#index', as: :trader_root
  end

  root 'pages#landing'

  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    },
    controllers: {
      sessions: 'users/sessions',
      invitations: 'users/invitations'
    },
    skip: [:registrations]

  # routes for user registrations controller
  devise_scope :user do
    get '/register', to: 'users/registrations#new', as: :new_user_registration
    get 'users/cancel', to: 'users/registrations#cancel', as: :cancel_user_registration
    get 'users/edit', to: 'users/registrations#edit', as: :edit_user_registration
    post 'users', to: 'users/registrations#create', as: :user_registration
    put 'users', to: 'users/registrations#update', as: :update_user_registration
    delete 'users', to: 'users/registrations#destroy', as: :destroy_user_registration
  end

  namespace :admin do
    resources :users, except: [:new, :create]
    resources :transactions, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :trader, path: 't' do
    resources :transactions, only: [:index]
    get 'dashboard', to: 'dashboard#index'
    get 'market', to: 'dashboard#market', as: :market_page
    get 'cash-in', to: 'cash_in#index'
    patch 'cash-in', to: 'cash_in#update'
    get 'withdraw', to: 'withdraw#index'
    patch 'withdraw', to: 'withdraw#update'
    get 'trade', to: 'trades#index'
    post 'trade/buy', to: 'trades#buy'
    post 'trade/sell', to: 'trades#sell'
    get 'portfolio', to: 'portfolios#index'
  end

  resources :statuses, only: [:edit, :update]

  # routes for static pages
  get 'landing', to: 'pages#landing', as: :landing_page
  get 'pending-verification', to: 'pages#pending_verification', as: :pending_verification_page

  # for route error
  match "*path", to: "application#no_path_found", via: :all
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < AdminsController
  layout 'admin_layout'

  def index
    @pending_traders = User.pending_traders
    @confirmed_email_traders = User.confirmed_email_traders
    @approved_traders = User.approved_traders

    @pagy, @confirmed_email_traders = pagy(@confirmed_email_traders, items: 8)
  end
end

app/controllers/trader/cash_in_controller.rb
class Trader::CashInController < TradersController
  before_action :ensure_frame_response, except: [:update]
  layout 'dashboard_layout'

  include CurrencyHelper

  def index
    @balance = current_user.balance
  end

  def update
    amount = params[:amount].to_f

    if Transaction.cash_in(current_user, amount)
      flash[:notice] = "Successfully cashed in #{format_currency(amount, unit: '$')}."
    else
      flash[:alert] = 'Failed to cash in. Please try again.'
    end
    redirect_to trader_dashboard_path
  end

  private

  def ensure_frame_response
    return if Rails.env.test?
    redirect_to trader_dashboard_path unless turbo_frame_request?
  end
end

app/controllers/trader/dashboard_controller.rb
class Trader::DashboardController < TradersController
  layout 'dashboard_layout'

  def index
    @total_portfolio_value = 0.0

    # Fetch quote for each stock
    @stock_quotes = {}
    @stocks.each do |stock|
      stock_symbol = stock[:stock_symbol]
      @stock_quotes[stock_symbol] = IEX::Api::Client.new.quote(stock_symbol)

      total_price = @stock_quotes[stock_symbol].latest_price * stock[:total_shares]
      @total_portfolio_value += total_price
    end
  end

  def market
  end

end

app/controllers/trader/portfolios_controller.rb
class Trader::PortfoliosController < TradersController
  layout 'dashboard_layout'

  def index
    @stocks = Stock.group_similar_stocks(current_user)

    if params[:sort_by] == 'asc'
      @stocks.sort_by! { |stock| stock[:total_shares] }
    elsif params[:sort_by] == 'desc'
      @stocks.sort_by! { |stock| -stock[:total_shares] }
    end

    @pagy, @stocks = pagy_array(@stocks) || pagy(@stocks) # pagy stuff
    @total_portfolio_value = 0.0

    # to fetch quote for each stock
    @stock_quotes = {}
    @stocks.each do |stock|
      stock_symbol = stock[:stock_symbol]
      @stock_quotes[stock_symbol] = IEX::Api::Client.new.quote(stock_symbol)

      total_price = @stock_quotes[stock_symbol].latest_price * stock[:total_shares]
      @total_portfolio_value += total_price
    end
  end
end

app/controllers/trader/trade_controller.rb
class Trader::TradeController < ApplicationController
  layout 'dashboard_layout'

  def index
    @trader_status = current_user.status&.status_type
    return unless params[:symbol].present?

    @stock_symbol = params[:symbol].to_s.upcase

    begin
      @data = IEX::Api::Client.new.quote(@stock_symbol)
    rescue IEX::Errors::SymbolNotFoundError => e
      flash[:alert] = "Stock symbol not found: #{@stock_symbol}"
      redirect_to trader_trade_path
    end
  end

  def buy
    @stock_symbol = params[:symbol].to_s.upcase
    @data = IEX::Api::Client.new.quote(@stock_symbol)
    shares = params[:shares].to_i
    price_per_share = @data.latest_price
    total_cost = price_per_share * shares

    if current_user.balance >= total_cost
      # Update user's balance
      current_user.update(balance: current_user.balance - total_cost)
      flash[:notice] = 'Stock purchased successfully'
      # Record the transaction
      Transaction.create!(
        user: current_user,
        transaction_type: 'buy',
        stock_symbol: @data.symbol,
        shares:,
        price_per_share:
      )

    else
      flash[:alert] = 'Insufficient balance'
    end
  end
end

app/controllers/trader/trades_controller.rb
class Trader::TradesController < TradersController
  before_action :set_params
  layout 'dashboard_layout'

  def index
    return unless params[:stock_symbol].present?
    @data = IEX::Api::Client.new.quote(@stock_symbol)
    @stock = Stock.find_by(stock_symbol: @stock_symbol)
    @total_shares = @stock ? @stock.total_shares(current_user) : 0.0

  rescue IEX::Errors::SymbolNotFoundError => e
    flash[:alert] = "NASDAQ symbol '#{@stock_symbol}' not found."
    redirect_to trader_trade_path
  end

  def buy
    if Transaction.buy_shares(current_user, @stock_symbol, @shares)
      flash[:notice] = "#{@stock_symbol} stock purchased successfully"
      redirect_to trader_portfolio_path
    else
      error_message = if current_user.errors.any?
                        current_user.errors.full_messages.join('. ')
                      else
                        'Oops. There was a problem in buying stock shares.'
                      end
      flash[:alert] = error_message
      redirect_back(fallback_location: trader_trade_path)
    end
  end

  def sell
    if Transaction.sell_shares(current_user, @stock_symbol, @shares)
      flash[:notice] = "#{@stock_symbol} stock sold successfully"
      redirect_to trader_portfolio_path
    else
      error_message = if current_user.errors.any?
                        current_user.errors.full_messages.join('. ')
                      else
                        'Oops. There was a problem in selling stock shares.'
                      end
      flash[:alert] = error_message
      redirect_back(fallback_location: trader_trade_path)
    end
  end

  private

  def set_params
    @stock_symbol = params[:stock_symbol].gsub(/[^a-zA-Z0-9\-.]/, '').upcase if params[:stock_symbol].present?
    @shares = params[:buy_shares].to_f if params[:buy_shares].present?
    @shares = params[:sell_shares].to_f if params[:sell_shares].present?
  end

end

app/controllers/trader/transactions_controller.rb
class Trader::TransactionsController < TradersController
  layout 'dashboard_layout'

  def index
    @transactions = current_user.transactions.includes(:stock).filter_by_type(params[:filter]).order(updated_at: :desc)
    @transaction_types = Transaction::TRANSACTION_TYPES
    @pagy, @transactions = pagy(@transactions)
  end
end

app/controllers/trader/withdraw_controller.rb
class Trader::WithdrawController < TradersController
  before_action :ensure_frame_response, except: [:update]
  layout 'dashboard_layout'

  include CurrencyHelper

  def index
    @balance = current_user.balance
  end

  def update
    amount = params[:amount].to_f

    if Transaction.withdraw(current_user, amount)
      flash[:notice] = "Successfully cashed out #{format_currency(amount, unit: '$')}."
    else
      flash[:alert] = 'Failed to withdraw. Please try again.'
    end
    redirect_to trader_dashboard_path
  end

  private

  def ensure_frame_response
    return if Rails.env.test?
    redirect_to trader_dashboard_path unless turbo_frame_request?
  end
end

app/controllers/traders_controller.rb
class TradersController < ApplicationController
  before_action :authorize_trader, :check_status, :set_trader_status, :set_stock_symbol, :set_stocks_per_trader

  private

  def authorize_trader
    redirect_to root_path, alert: "Access denied. You are not a trader." unless current_user.trader?
  end

  def check_status
    return unless current_user.trader? && @trader_status == 'pending' && !current_user.confirmed?

    sign_out(current_user)
    redirect_to pending_verification_page_path
  end

  def set_trader_status
    @trader_status = current_user.status&.status_type
  end

  def set_stock_symbol
    @stock_symbol = params[:stock_symbol].to_s.upcase
  end

  def set_stocks_per_trader
    @stocks = Stock.group_similar_stocks(current_user)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/trader/dashboard_helper.rb
module Trader::DashboardHelper
end

app/helpers/trader/withdraw_helper.rb
module Trader::WithdrawHelper
end

app/helpers/traders_helper.rb
module TradersHelper
end

app/views/trader/dashboard/_assets_box.html.erb
<div class="w-full min-h-fit rounded-2xl flex flex-col p-4">
  <h1 class="font-bold font-sans tracking-widest">
    <%= link_to trader_portfolio_path do %>
      <%= @stocks.count > 1 ? "My Assets" : "My Asset" %>
    <% end %>
  </h1>
  
  <% if @stocks.present? %>
    <div class="w-full grid--autofill px-0">
      <% @stocks.each do |stock| %>
        <div class="bg--frosted pt-6 pb-0 grid place-items-center">
          <%= render 'pages/widgets/solo_ticker', symbol: stock[:stock_symbol] %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="h-full w-full flex flex-col gap-1 p-4 text-sm">
      <p>You currently don't own any assets</p>
      <small>
        <%= link_to 'Start your journey here.', trader_trade_path, class: "shared_links" %>
      </small>
    </div>
  <% end %>
    
</div>

app/views/trader/dashboard/_balance_box.html.erb
<div class="balance-box rounded-xl border-2 border-gray-600 w-full flex items-center justify-between px-4 py-6">
  <div class="flex flex-col gap-2">
    <h2 class="font-semibold font-sans tracking-widest opacity-70">Available Balance</h2>
    <div class="flex gap-2 items-end">
      <h1 class="text-xl sm:text-3xl flex gap-1">    
        <small class="text-sm p-1 font-sans">$</small>  
        <%= format_currency(current_user.balance) %>
      </h1>
      <small class="text-sm p-1 font-sans">USD</small>  
    </div>
    
  </div>
  <div class="flex items-center justify-between gap-2">
    <%= link_to "Cash-in", trader_cash_in_path, data: { turbo_frame: 'cash_in_modal' }, class: "cash-in-btn modal__button button--green mt-0" %>
    <%= link_to "Withdraw", trader_withdraw_path, data: { turbo_frame: 'withdraw_modal' }, class: "withdraw-btn modal__button button--purple mt-0" %>
  </div>
</div>

app/views/trader/dashboard/_pending_banner.html.erb
<div id="bottom-banner" tabindex="-1" class="absolute bottom-0 start-0 z-50 flex justify-between w-full p-4 border-t bg-stone-950 border-gray-600 rounded-2xl">
    <div class="flex items-center mx-auto">
        <div class="flex flex-col items-center text-sm font-normal text-gray-400">
          <h3 class="text-gray-300 font-bold tracking-widest">We're currently evaluating your account.</h3>
          <small class="pt-2">Kindly wait for the confirmation email regarding the status of your account.</small>
          <small>You can browse through the market page in the meantime.</small>
        </div>
    </div>
    <div class="flex items-center">
        <button data-dismiss-target="#bottom-banner" type="button" class="flex-shrink-0 inline-flex justify-center w-7 h-7 items-center text-gray-400 hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 dark:hover:bg-gray-600 dark:hover:text-white">
            <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
            </svg>
            <span class="sr-only">Close banner</span>
        </button>
    </div>
</div>

app/views/trader/dashboard/_profile_box.html.erb
<div class="profile-box w-full h-1/10 flex flex-col sm:flex-row items-center gap-4 ps-4 py-4">
  <div class="w-full sm:w-1/3 h-full flex items-center gap-3 sm:border-r-2 border-gray-600">
    <% if current_user.admin? %>
      <%= image_tag("cat_avatar.png", alt: "user photo", class: "size-10 rounded-full ring-4 ring-amber-700") %>
    <% else %>
      <% ring_color_class = @trader_status == "approved" ? "ring-primary/55" : "ring-accent/55" %>
      <%= image_tag("fox_avatar.png", alt: "user photo", class: "size-10 rounded-full ring-4 #{ring_color_class}") %>
    <% end %>
    <div class="font-bold flex flex-col gap-3">
      <h1 class="w-full flex items-center gap-3">
        <%= current_user.username %>
        <% if @trader_status == "approved" %>
          <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 21 21">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m6.072 10.072 2 2 6-4m3.586 4.314.9-.9a2 2 0 0 0 0-2.828l-.9-.9a2 2 0 0 1-.586-1.414V5.072a2 2 0 0 0-2-2H13.8a2 2 0 0 1-1.414-.586l-.9-.9a2 2 0 0 0-2.828 0l-.9.9a2 2 0 0 1-1.414.586H5.072a2 2 0 0 0-2 2v1.272a2 2 0 0 1-.586 1.414l-.9.9a2 2 0 0 0 0 2.828l.9.9a2 2 0 0 1 .586 1.414v1.272a2 2 0 0 0 2 2h1.272a2 2 0 0 1 1.414.586l.9.9a2 2 0 0 0 2.828 0l.9-.9a2 2 0 0 1 1.414-.586h1.272a2 2 0 0 0 2-2V13.8a2 2 0 0 1 .586-1.414Z"/>
          </svg>
        <% end %>
      </h1>
      <small>
        <%= current_user.email %>
      </small>
    </div>
  </div>
  <div class="hidden w-2/3 sm:flex flex-col sm:flex-row justify-around gap-3 text-sm">
    <div class="flex flex-col gap-3">
      <small>User ID:</small>
      <h1 class="font-bold">
        <%= current_user.uid %>
      </h1>
    </div>
    <div class="flex flex-col gap-3">
      <small>Account Status:</small>
      <h1 class="font-bold">
        <%= @trader_status == "approved" ? "All-access" : "Pending Approval"  %>
      </h1>
    </div>
    <div class="flex flex-col gap-3">
      <small>User Type:</small>
      <h1 class="font-bold">
        <%= current_user.role.capitalize %>
      </h1>
    </div>
  </div>
</div>

app/views/trader/dashboard/index.html.erb
<% content_for :header do %>
  Hello, <%= time_of_day_greeting.downcase %>
<% end %>
<div class="relative w-full h-full p-2 flex flex-col gap-2">
  <div class="px-4">
    <%= render 'profile_box' %>
  </div>
  <% if @trader_status != "approved" %>
    <%= render 'pending_banner' %>
    <!-- *** STATUS_TYPE: APPROVED *** -->
  <% else %>
    <div class="px-4">
      <%= render 'balance_box' %>
    </div>
    <%= render 'assets_box' %>
  <% end %>
</div>
<!--** TURBO_FRAME MODALS **-->
<%= turbo_frame_tag "cash_in_modal" %>
<%= turbo_frame_tag "withdraw_modal" %>

app/views/trader/dashboard/market.html.erb
<% content_for :header do %>
  Markets Overview
  <p class="text-base text-gray-500">
    Trading Data
  </p>
<% end %>
<div class="w-full h-full flex flex-col lg:flex-row items-center gap-2">
  <div class="w-full lg:w-3/4 h-full flex flex-col items-center gap-2">
    <%= render 'pages/widgets/market_data_overview' %>
  </div>
  <div class="w-full lg:w-1/4 h-full lg:px-2 lg:border-l-2 lg:border-gray-600 flex flex-col">
    <div class="h-1/2 w-full">
      <%= render 'pages/widgets/top_news' %>
    </div>
    <div class="h-1/2 w-full">
      <%= render 'pages/widgets/stock_market' %>
    </div>
  </div>
</div>